vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        painting_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/assets/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
